languageCode = "en"
languageName = "English"
weight = 1
title = "Learn Tinker Share Blog"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "A blog about AI engineering, development, and best practices"
  mainSections = ["posts"]

[params.author]
  name = "Charles Thayer"
  headline = "AI Engineer & Founder"
  bio = "Software engineer exploring AI, and best practices"
  # image = "/images/thayer-head-2026-purple.jpg"
  social = ["https://thayer.b2si.com", "https://linkedin.com/in/cgthayer"]
