baseURL = 'https://blog.learntinkershare.ai/'
languageCode = 'en-us'
title = 'Learn Tinker Share Blog'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown
